CREATE SEQUENCE SEQ_CAR;

CREATE TABLE TBL_CAR(
	ID NUMBER CONSTRAINT PK_CAR PRIMARY KEY,
	BRAND VARCHAR2(255) NOT NULL,
	MODEL VARCHAR2(255) NOT NULL,
	PRICE NUMBER NOT NULL,
	RELEASED_DATE DATE NOT NULL,
);

ALTER TABLE TBL_CAR ADD(CREATED_DATE DATE DEFAULT SYSDATE);
ALTER TABLE TBL_CAR ADD(UPDATED_DATE DATE DEFAULT SYSDATE);