CREATE SEQUENCE SEQ_OWNER;

CREATE TABLE TBL_OWNER(
	ID NUMBER CONSTRAINT PK_OWNER PRIMARY KEY,
	NAME VARCHAR2(255) NOT NULL,
	PHONE VARCHAR2(255) NOT NULL,
	ADDRESS VARCHAR2(255) NOT NULL
);

ALTER TABLE TBL_OWNER ADD(CREATED_DATE DATE DEFAULT SYSDATE);
ALTER TABLE TBL_OWNER ADD(UPDATED_DATE DATE DEFAULT SYSDATE);