CREATE SEQUENCE SEQ_REGISTRATION;

CREATE TABLE TBL_REGISTRATION(
	ID NUMBER CONSTRAINT PK_REGISTRATION PRIMARY KEY,
	CAR_ID NUMBER NOT NULL,
	OWNER_ID NUMBER NOT NULL,
	CREATED_DATE DATE DEFAULT SYSDATE,
	UPDATED_DATE DATE DEFAULT SYSDATE,
	CONSTRAINT FK_REGISTRAION_CAR FOREIGN KEY(CAR_ID)
	REFERENCES TBL_CAR(ID),
	CONSTRAINT FK_REGISTRAION_OWNER FOREIGN KEY(OWNER_ID)
	REFERENCES TBL_OWNER(ID)
);